local state = require("tabterm.state")

local M = {}

local scripts = {
	bash = "shell/bash.bash",
	zsh = "shell/zsh.zsh",
}

---@param value any
---@return string
local function shell_quote(value)
	return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
end

---@param path string
---@return string
local function parent_dir(path)
	return vim.fn.fnamemodify(path, ":h")
end

---@param path string
---@param lines string[]
---@return boolean
local function write_file(path, lines)
	vim.fn.mkdir(parent_dir(path), "p")
	return vim.fn.writefile(lines, path) == 0
end

---@param cmd string?
---@return string?
function M.shell_name(cmd)
	local executable = tostring(cmd or ""):match("^%s*(%S+)")
	if not executable or executable == "" then
		return nil
	end

	local name = vim.fn.fnamemodify(executable, ":t"):gsub("^-", "")
	if scripts[name] then
		return name
	end

	return nil
end

---@param shell string
---@return string?
local function script_path(shell)
	local matches = vim.api.nvim_get_runtime_file(scripts[shell], false)
	return matches[1]
end

---@param shell string
---@return string
local function cache_dir(shell)
	return vim.fn.stdpath("cache") .. "/tabterm/shell-integration/" .. shell
end

---@param terminal tabterm.Terminal
---@return boolean
---@return string? shell
local function is_enabled(terminal)
	if terminal.spec.kind ~= "shell" then
		return false, nil
	end

	local current = state.config
	if not current or not current.shell_integration or not current.shell_integration.enabled then
		return false, nil
	end

	local shell = M.shell_name(terminal.spec.cmd)
	if not shell then
		return false, nil
	end

	return current.shell_integration.shells[shell] == true, shell
end

---@param shell_cmd string
---@param integration_script string
---@return table
---@return table<string,string>?
local function bash_job(shell_cmd, integration_script)
	local rcfile = cache_dir("bash") .. "/bashrc"
	write_file(rcfile, {
		"# Generated by tabterm. Do not edit.",
		'if [[ -r "${HOME}/.bashrc" ]]; then',
		'  source "${HOME}/.bashrc"',
		"fi",
		"source " .. shell_quote(integration_script),
	})
	if vim.fn.filereadable(rcfile) ~= 1 then
		return { shell_cmd }, nil
	end

	return { shell_cmd, "--rcfile", rcfile, "-i" }, nil
end

---@param shell_cmd string
---@param integration_script string
---@return table
---@return table<string,string>
local function zsh_job(shell_cmd, integration_script)
	local dir = cache_dir("zsh")
	local zshrc = dir .. "/.zshrc"
	write_file(zshrc, {
		"# Generated by tabterm. Do not edit.",
		'if [[ -n "${TABTERM_ORIGINAL_ZDOTDIR:-}" ]]; then',
		'  export ZDOTDIR="$TABTERM_ORIGINAL_ZDOTDIR"',
		"else",
		"  unset ZDOTDIR",
		"fi",
		'if [[ -r "${ZDOTDIR:-$HOME}/.zshrc" ]]; then',
		'  source "${ZDOTDIR:-$HOME}/.zshrc"',
		"fi",
		"source " .. shell_quote(integration_script),
	})
	if vim.fn.filereadable(zshrc) ~= 1 then
		return { shell_cmd }, nil
	end

	return { shell_cmd }, {
		ZDOTDIR = dir,
		TABTERM_ORIGINAL_ZDOTDIR = vim.env.ZDOTDIR or "",
	}
end

---@param terminal tabterm.Terminal
---@return table job_cmd
---@return table<string,string>? job_env
function M.job(terminal)
	local enabled, shell = is_enabled(terminal)
	if not enabled or not shell then
		return { terminal.spec.cmd }, nil
	end

	local integration_script = script_path(shell)
	if not integration_script then
		return { terminal.spec.cmd }, nil
	end

	if shell == "bash" then
		return bash_job(terminal.spec.cmd, integration_script)
	elseif shell == "zsh" then
		return zsh_job(terminal.spec.cmd, integration_script)
	end

	return { terminal.spec.cmd }, nil
end

return M
